// <auto-generated />
using System;
using DnDAPI.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DnDAPI.Models.Entities.DungeonMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GamePreferencesId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperiance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GamePreferencesId");

                    b.ToTable("DungeonMasters");
                });

            modelBuilder.Entity("DnDAPI.Models.Entities.GamePreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AdvancedDnD1E")
                        .HasColumnType("bit");

                    b.Property<bool>("AdvancedDnD2E")
                        .HasColumnType("bit");

                    b.Property<bool>("DungeonAndDragons1E")
                        .HasColumnType("bit");

                    b.Property<bool>("DungeonAndDragons3E")
                        .HasColumnType("bit");

                    b.Property<bool>("DungeonAndDragons4E")
                        .HasColumnType("bit");

                    b.Property<bool>("DungeonAndDragons5E")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GamePreferences");
                });

            modelBuilder.Entity("DnDAPI.Models.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DungeonMasterId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GamePreferencesId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperiance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DungeonMasterId");

                    b.HasIndex("GamePreferencesId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DnDAPI.Models.Entities.DungeonMaster", b =>
                {
                    b.HasOne("DnDAPI.Models.Entities.GamePreferences", "GamePreferences")
                        .WithMany()
                        .HasForeignKey("GamePreferencesId");

                    b.Navigation("GamePreferences");
                });

            modelBuilder.Entity("DnDAPI.Models.Entities.Player", b =>
                {
                    b.HasOne("DnDAPI.Models.Entities.DungeonMaster", "DungeonMaster")
                        .WithMany("Players")
                        .HasForeignKey("DungeonMasterId");

                    b.HasOne("DnDAPI.Models.Entities.GamePreferences", "GamePreferences")
                        .WithMany()
                        .HasForeignKey("GamePreferencesId");

                    b.Navigation("DungeonMaster");

                    b.Navigation("GamePreferences");
                });

            modelBuilder.Entity("DnDAPI.Models.Entities.DungeonMaster", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
